### PR TITLE
fix: 462 - Fix Header.Avatar display - closes #462

### LINKED ISSUE #462: Issues using Header.Avatar
Header.Avatar has a few issues:

1. When used in a header, it should be documented that it goes inside `BaseHeaderNavigation`.
2. The avatar component itself is in a div, but when included in header navigation, it is erroneously put inside the `ul` tag

It is likely that the Avatar information should be included as props to `BaseHeader` instead of being provided as a component since the positioning of it is highly specific. Either that, or detect when an `Header.Avatar` component is included as a child of `BaseHeaderNavigation` and place it outside the generated `ul` tag.

### PR DESCRIPTION
**Pull request by athill**
The `Header.Avatar` and `Header.Search` components need to be rendered inside the `BaseHeaderNavigation`'s `nav` component, but outside of the navigation `ul`, which was not happening previously.

This change allows the search and avatar components to be added as children to `BaseHeaderNavigation` and the various types of components are placed in their respective locations.

### CODE REVIEW

File: src/components/Alert/Alert.jsx [hunk 1]
```diff
@@ -88,9 +88,9 @@ Alert.propTypes = {
   /** [Developer] Adds data-testId attributes for component testing */
   testMode: PropTypes.bool,
   /** An extremely brief title for the alert */
-  title: PropTypes.oneOfType([PropTypes.string, PropTypes.element]).isRequired,
```
Comment (athill) [inline src/components/Alert/Alert.jsx:91]: There is a test that `title` is not required, but it was still required. This fixes that.

File: src/components/Header/BaseHeader.md [hunk 2]
```diff
@@ -62,9 +62,9 @@ const secondaryNavigation = <BaseHeaderNavigationSecondary title="Component Libr
                     <BaseHeaderMenuItem itemUrl="#" subMenu>Sub item three</BaseHeaderMenuItem>
                 </BaseHeaderMenu>
             </BaseHeaderMenuItem>
+            <Header.Search action={"/mySearchURL"} method={"post"} />
+            <Header.Avatar username={"johndoe"} shortName={"jd"} logoutURL={"/logout"} />
     </BaseHeaderNavigation>
-    <Header.Search action={"/mySearchURL"} method={"post"} />
-    <Header.Avatar username={"johndoe"} shortName={"jd"} logoutURL={"/logout"} />
```
Comment (athill) [inline src/components/Header/BaseHeader.md:67]: `Header.Search` and `Header.Avatar` need to be children of `BaseHeaderNavigation`

File: src/components/Header/BaseHeader.test.jsx [hunk 3]
```diff
@@ -62,24 +62,29 @@ describe("<BaseHeader />", () => {
...
-            </BaseHeaderMenu>
+            <BaseHeaderMenuItem>
+              <BaseHeaderMenu label="Nav item three">
+                <BaseHeaderMenuItem href={"#"}>Sub item one</BaseHeaderMenuItem>
+                <BaseHeaderMenuItem href={"#"}>Sub item two</BaseHeaderMenuItem>
+                <BaseHeaderMenuItem href={"#"}>
+                  Sub item three
+                </BaseHeaderMenuItem>
+              </BaseHeaderMenu>
+            </BaseHeaderMenuItem>
```
Comment (athill) [inline src/components/Header/BaseHeader.test.jsx:87]: `BaseHeaderMenu` needs to be wrapped in a `BaseHeaderMenuItem` for its output to match the `rivet` examples. Having it as a child of `BaseHeaderNavigation` is now disallowed via its prop types

File: src/components/Header/BaseHeaderNavigation.jsx [hunk 4]
```diff
@@ -84,9 +99,8 @@ const BaseHeaderNavigation = ({ children, testMode = false, ...attrs }) => {
         hidden={!isNavMenuOpen}
         {...(testMode && { "data-testid": TestUtils.Header.headerNavTestId })}
       >
-        <ul className={"rvt-header-menu__list"}>
-          {children}
-        </ul>
+        <ul className={"rvt-header-menu__list"}>{listItems}</ul>
```
Comment (burnumd) [inline src/components/Header/BaseHeaderNavigation.jsx:102]:
```suggestion
        <ul className="rvt-header-menu__list">{listItems}</ul>
```

File: src/components/Header/BaseHeaderNavigation.test.jsx [hunk 5]
```diff
@@ -22,21 +24,15 @@ describe("<BaseHeaderNavigation />", () => {
...
-          </ul>
+          <BaseHeaderMenuItem itemUrl="#">Nav item one</BaseHeaderMenuItem>
+          <BaseHeaderMenuItem itemUrl="#">Nav item two</BaseHeaderMenuItem>
+          <BaseHeaderMenuItem>
+            <BaseHeaderMenu label="Nav item three">
+              <a href={"#"}>Sub item one</a>
+              <a href={"#"}>Sub item two</a>
+              <a href={"#"}>Sub item three</a>
+            </BaseHeaderMenu>
+          </BaseHeaderMenuItem>
```
Comment (athill) [inline src/components/Header/BaseHeaderNavigation.test.jsx:35]: `BaseHeaderNavigation` now restricts the component types it allows as its children. This was also incorrect HTML, as `BaseHeaderNavigation` generates a `ul` tag, so this basically had nested `ul` tags.

File: src/components/Header/BaseHeaderNavigation.jsx [hunk 6]
```diff
@@ -65,14 +67,27 @@ const BaseHeaderNavigation = ({ children, testMode = false, ...attrs }) => {
     }
   };
 
+  // Avatar and Search components need to be rendered inside the nav tag, but outside of the list
+  const listItems = [];
+  const otherHeaderMenuItems = [];
+  React.Children.forEach(children, (child) => {
+    if ([Header.Avatar, Header.Search].includes(child.type)) {
```
Comment (burnumd) [inline src/components/Header/BaseHeaderNavigation.jsx:74]: I think it may make more sense to reverse the sense of this test. That is, if the child is a `BaseHeaderMenuItem` add it to the `listItems` and otherwise it goes outside the list. Since we know `BaseHeaderMenuItem` is wrapped in a `li`, it can go in the list and any additional content is outside the list content.

**Review by burnumd — CHANGES_REQUESTED** [review]

File: src/components/Header/BaseHeaderNavigation.jsx (hunk 6 above)
Comment (athill) [reply src/components/Header/BaseHeaderNavigation.jsx]: Works for me. Done. Thanks.

**Review by burnumd — APPROVED** [review]

File: src/components/File/File.test.jsx [hunk 7]
```diff
@@ -88,7 +88,9 @@ describe("<File />", () => {
       expect(description.innerHTML).toBe("2 files selected");
     });
 
-    it("should allow resetting if embedded in a form", async () => {
+    // This test is flaky and unreliable. We should manually verify the expected behavior when
+    // making changes or updating dependencies
+    it.skip("should allow resetting if embedded in a form", async () => {
```
Comment (burnumd) [inline src/components/File/File.test.jsx:93]: @pcberg @johglove, I wanted to double check that y'all are ok with this change. It narrowly impacts coverage, but the test failing only occasionally impacts development and DX and this branch can be manually tested during dependency updates.

Comment (pcberg) [reply src/components/File/File.test.jsx:93]: No objections from me.
